### ISSUE TITLE
Cannot figure out exactly where to put the webfonts

### ISSUE THREAD

**Issue by mattstratton** [nishanths/cocoa-hugo-theme#1]
I have purchased the `ProximaNova` fonts, and copied them into `static\webfonts` inside the theme directory. They build properly into the `public\static\webfonts` directory on my site, however, they 404 when I try to hit them on a URL. I'm not quite able to see if the proper font is being used. The site in question is http://mattstratton.io.

**Comment by nishanths** [comment]
Apologies for not responding earlier. I accidentally missed this. You were quite close — place the `webfonts` directory in `static/css/` instead of just `static/`.

**Comment by nishanths** [comment]
@mattstratton Any luck with this? Let me know if there is something I should address.
