### ISSUE TITLE
Support for separating blogs by month

### ISSUE THREAD

**Issue by andy4thehuynh** [nishanths/cocoa-hugo-theme#10]
My blog posts will add up quickly on one page. It will look daunting to see a small list like that without organization. 

Would organizing the blogposts by month be in your future plans for this project? I can get started on it if you feel this is the direction you want.

**Comment by nishanths** [comment]
Thank you. Feel free to get started!

**Comment by lpancescu** [comment]
I would like to propose a solution, splitting just the blog page in sections (by year or by month), and limiting the number of posts displayed on the home page, with a "See more" link. Everything configurable in config.toml, so we don't break existing sites.

There's still room for improvement: when splitting the posts in sections, the year is repeated both in the section title and for each post. I'm not sure how to pass additional variables through the context to the `li.html` partial (probably via Scratch), and the logic becomes pretty complex.
