### ISSUE TITLE
Support for comment functionality

### ISSUE THREAD

**Issue by pingrunhuang** [nishanths/cocoa-hugo-theme#101]
Hey, I am currently using cocoa hugo theme for my blog. And I always wanted to have a comment section to communicate with my readers. Since I am in China, the disqus is blocked by the GFW. I have searched for several alternative and others might require building you own database which is not suitable for a static page hosted on github. So I add a gitalk functionality to the theme wondering if you want me to add that functionality to the theme.

**Comment by nishanths** [comment]
@pingrunhuang yes, for sure. please make a pull request when you find a chance! (and @mention me if possible so that I can make sure to look at it)

**Comment by nishanths** [comment]
I would recommend looking at the existing `piwik` implementation, if you're looking for a pattern to follow

**Comment by pingrunhuang** [comment]
Hey @nishanths , so glad to hear from you. I currently have met a problem of managing my own hugo project and the cocoa theme project. I am treating the cocoa theme project as a submodule in git. But the problem is I have made some customized modification to the cocoa theme to fit into my use.  Which means I have the following structure for my project:
```
- theme
  - cocoa-hugo-theme
  - customized-cocoa
```
Since I have to much customized stuff in the `customized-cocoa`, I don't want to mess up the original cocoa theme. Do you have some idea how I can sync the work I do that I want to contribute to the customized-cocoa? In other words, how can I just commit part on my work to the origin cocoa theme? 
I am currently copy paste manually to the `cocoa-hugo-theme`.

**Comment by pingrunhuang** [comment]
@nishanths , glad to hear from you. Can I work on the misc branch or do I need to create a new branch?

**Comment by nishanths** [comment]
@pingrunhuang please create a new branch. I don't think GitHub will let you push to the `misc` branch.

Typically, contributors do the following:
- create a fork of the repository on GitHub
- clone the forked repository and work on it (creating branches as they like)
- push the branches to the forked repository
- open a pull request from a branch on the forked repository to the `master` branch of this repository.

Let me know if I can clarify.

**Comment by nishanths** [comment]
closed via #103
