### ISSUE TITLE
Linkedin and twitter icons not displayed

### ISSUE THREAD

**Issue by gtpedrosa** [nishanths/cocoa-hugo-theme#117]
I just cloned the repository and ran `hugo server` on the example website. However the linkedin and twitter icons appear with `style = "display: none !Important;" ` in the html file. Coincidently both are missing from the example page, as shown below.

![screenshot from 2017-12-02 18-52-31](https://user-images.githubusercontent.com/5048784/33520057-439f4ef8-d792-11e7-89fb-6754c7c270e6.png)

I don't believe this behaviour is intended. Anyone can point me at the right track on this? My hugo version is v0.31 linux amd64.

**Comment by nishanths** [comment]
This isn't the intended behavior, but sadly I'm unable to reproduce on `v0.32-DEV darwin/amd64` and on `v0.30.2 darwin/amd64`. The demo site doesn't have the issue either. https://themes.gohugo.io/theme/cocoa/.

Couple of things to try:
- Check if you have local modifications to your copy of theme.
- If you have a link to a repo with your website's Hugo source code, I can take a look.

**Comment by nishanths** [comment]
this is a wild guess, but maybe you have a browser extension/script that hides social icons?

**Comment by gtpedrosa** [comment]
@nishanths Thanks for the feedback. I have: 

* made no modifications in the theme for this example
* created a [repository with the code used in the example](https://github.com/gtpedrosa/example_cocoa) 

I got ahold another machine today and couldn't reproduce the issue with Hugo v0.30.2 windows/amd64 either. Both icons show without problem. Here is the output with the same source code:

![image](https://user-images.githubusercontent.com/5048784/33565653-7be8fd20-d8fc-11e7-9cff-0d4ffe49a2fd.png)

I'll take a look at my browser extensions, I haven't thought about that. If any extension is blocking it sure is a unintended side effect since I haven't installed any extension with that purpose.

**Comment by gtpedrosa** [comment]
@nishants You were right about the extension. I am using adblock for firefox and it has an option to block social media icons tracking. After disabling it the icons showed up normally. Here's the option disabled:


![adblock](https://user-images.githubusercontent.com/5048784/33748690-b23cc114-dba8-11e7-8dc2-e4d588c21d8d.png)

It is strange that with the hugo theme I used previously this did not happen. Anyway thank you for pointing me to the right track. Keep up the good work ;)

**Comment by nishanths** [comment]
Thanks. Glad that worked out.
