### ISSUE TITLE
Add Telegram icon

### ISSUE THREAD

**Issue by scriptnull** [nishanths/cocoa-hugo-theme#128]
It would be good to have a Telegram icon at the bottom as on of the communication methods.

![image](https://user-images.githubusercontent.com/4211715/39097259-95f08376-4677-11e8-8b6c-9a7255e1324e.png)

It will be pointing to t.me/telegram_username

**Comment by nishanths** [comment]
I'm open to PRs that add the icon, with the option to configure it in `config.toml` (similar to existing icons). Relates to #50.

**Comment by UtkarshVerma** [comment]
@nishanths Done!
