### ISSUE TITLE
Adding Content Troubles

### ISSUE THREAD

**Issue by nimdajitam** [nishanths/cocoa-hugo-theme#13]
I've installed hugo, created new site, grabbed down cocoa and followed the instructions in it's readme. Adding new content as instructed doesn't produce wroking site at the end. Is there a bug or some sort of mistake made druing transition from old verision? If I move content folder from example site and it's config to mine, it works but as soon as I add new content (for ex.: new blog entry) it messes up displaying part of the front page, where blog titles should be displayed and link doesn't appear at all.

**Comment by nishanths** [comment]
thanks for reporting! will look into this tonight.

**Comment by nishanths** [comment]
**TLDR**: Set `draft = false` in the new post's front matter to make the link appear.

# 

**Long version**

With 

```
$ hugo version
Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T07:37:59-05:00
```

I did the following commands:

```
$ hugo new site example
$ cd example
$ git clone https://github.com/nishanths/cocoa-hugo-theme.git themes/cocoa
```

Then copy `config.toml` and `content` from the theme:

```
$ cp -r themes/cocoa/content/* content/
$ cp themes/cocoa/config.toml .
```

Finally, created new post:

```
$ hugo new blog/your-new-post.md
```

Set `draft = false` in `content/blog/your-new-post.md` to make the link appear on front page.

(Don't forget to run `hugo -t cocoa` to regenerate.)

**Comment by nishanths** [comment]
did not encounter the issue you described of parts of front page messing up. could you provide more details? thanks.

**Comment by nimdajitam** [comment]
I'm very sorry for the trouble. I forgot to set draft parameter to false!

**Comment by nimdajitam** [comment]
Moreover, when not regenerating content while running the server serving it, dates are not displayed correctly. This was apparently my mistake too. Thanks.

**Comment by nishanths** [comment]
You're welcome :)
