### ISSUE TITLE
LATEST POSTS show folders, not articles？

### ISSUE THREAD

**Issue by hijulian** [nishanths/cocoa-hugo-theme#147]
![image](https://user-images.githubusercontent.com/6925683/69899914-c7286180-13a7-11ea-9dda-184fcc3fa546.png)

**Comment by nishanths** [comment]
Thanks for reporting!

This should now be fixed in https://github.com/nishanths/cocoa-hugo-theme/commit/b005f54b90c4e70a1c7cb94140e94503fbc45c44.
