### ISSUE TITLE
error using cocoa theme

### ISSUE THREAD

**Issue by svsmailus** [nishanths/cocoa-hugo-theme#15]
Hi when I run:
`hugo -t cocoa`

I get:

`Started building site
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
ERROR: 2016/09/30 17:42:25 template.go:131: template: theme/partials/li.html:2:43: executing "theme/partials/li.html" at <.Site.Params.DateFor...>: invalid value; expected string in theme/partials/li.html
`

Other themes are working.

**Comment by nishanths** [comment]
Could you try using the `config.toml` from the exampleSite:
https://github.com/nishanths/cocoa-hugo-theme/blob/master/exampleSite/config.toml

**Comment by svsmailus** [comment]
That fixed it.

It needs the pygmentsuseclasses and date forms.
