### ISSUE TITLE
Use .BaseURL instead of .BaseUrl

### ISSUE THREAD

**Issue by digitalcraftsman** [nishanths/cocoa-hugo-theme#2]
In Hugo 0.14, `BaseUrl` was renamed to `.BaseURL`. The old name is still available as an alias that triggers a warning. But with the upcoming version 0.15 will remove the aliases.

Check out your [head.html](https://github.com/nishanths/cocoa-hugo-theme/blob/56dc02acc3081d114007937b83c3bea78fa54538/layouts/partials/head.html) partial to update it. Otherwise is it not possible to generate your theme with future releases.

**Comment by bep** [comment]
And this is, by the way, the reason why there is no demo for this theme on themes.gohugo.io.

**Comment by nishanths** [comment]
Thanks @digitalcraftsman and @bep!

**Comment by bep** [comment]
There is still one BaseUrl in single.html ...

**Comment by nishanths** [comment]
Thanks. Now fixed on `master`.
