### ISSUE TITLE
Option to add an avatar

### ISSUE THREAD

**Issue by tristan-k** [nishanths/cocoa-hugo-theme#22]
Please add a option to add an avatar to the landingpage. For example like in http://themes.gohugo.io/theme/hugo-sustain/ or in http://themes.gohugo.io/theme/hugo-goa/

![cocoa_avatar](https://cloud.githubusercontent.com/assets/732025/19643424/87989f7e-99ea-11e6-9b0c-e55ebca7b1a1.jpg)

**Comment by remeh** [comment]
Hello. If you still want this feature: implemented here https://github.com/nishanths/cocoa-hugo-theme/pull/25

But you would need to change `?s=50` to something bigger if you want a large gravatar such as the one in your screenshot.

**Comment by nishanths** [comment]
Closed via #25

**Comment by tristan-k** [comment]
How do I use this with a local image?

**Comment by remeh** [comment]
Hm right I did focus on Gravatar support, sorry I was a bit off-topic with your issue.
We could imagine having another configuration entry such as "Avatar" in the config.toml refering to an image and using this instead of the "Gravatar" one. @nishanths would you accept such a change ? If yes I'll do it.

**Comment by nishanths** [comment]
@remeh yes :)

**Comment by remeh** [comment]
@tristan-k Available https://github.com/nishanths/cocoa-hugo-theme/pull/26

If you want a larger size than the default one, for example `150px`, you should use the CSS override option using `ExtraCssFiles` and put:

```
.avatar {
  max-width: 150px;
}
```

in your custom css file.

**Comment by tristan-k** [comment]
Doesnt work for me. The avatar will not be shown. I double checked the path to `img/avatar.png`.

```
baseurl = "https://url.tld" 
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Arthur Dent"
title = "Arthur Dent"
# pygmentsuseclasses = ture
# disqusShortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Arthur Dent"
# Gravatar = "" # do not use in the same time as Avatar
Avatar = "img/avatar.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Don't panic"
Email = "you@example.space"
FaviconFile = "img/leaf.ico"
# GATracker = "XYZ"
# GitHub = "//github.com/you"
HighlightJS = true
Initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
# LinkedIn = "//linkedin.com/in/you"
# Twitter = "//twitter.com/you"

ExtraCssFiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
```

**Comment by remeh** [comment]
OK. Do you confirm that you've put it in `static/img/avatar.png` ?

**Comment by tristan-k** [comment]
Yes.

**Comment by remeh** [comment]
That is weird. Here it works well with a project completely started from scratch

![screenshot_2016-11-09_21-20-27](https://cloud.githubusercontent.com/assets/1798689/20153331/8bbc151a-a6c2-11e6-9c70-f8bc68fda633.png)

**Comment by nishanths** [comment]
@tristan-k is there a 404 in the browser console when fetching the image?
