### ISSUE TITLE
cachebuster the wrong way around?

### ISSUE THREAD

**Issue by robinst** [nishanths/cocoa-hugo-theme#32]
Setting `params.cachebuster` to `true` results in links like this:

    <link rel="stylesheet" href="/css/reset.css">

Setting it to `false` uses the unix timestamp as a query param, see [here](https://github.com/nishanths/cocoa-hugo-theme/blob/master/layouts/partials/head_includes.html#L18). This means clients will have to load the files again when the site is rebuilt. Isn't that supposed to be "cache busting"? Seems the wrong way around.

**Comment by nishanths** [comment]
Thanks for catching. Yes, I made a mistake in this commit: https://github.com/nishanths/cocoa-hugo-theme/commit/6e2e423beca2dbd59e71e2c262cc95f4d6004380

**Comment by robinst** [comment]
Thanks :). With cachebusting turned on, I now get this:

> ERROR: 2016/12/04 15:56:32 template.go:132: template: theme/partials/head_includes.html:25:46: executing "theme/partials/head_includes.html" at <.Now.Unix>: can't evaluate field Now in type interface {} in theme/partials/head_includes.html

**Comment by nishanths** [comment]
Thanks! It looks like `.Now` [does not exist any more](https://github.com/spf13/hugo/issues/314). Sigh, it was undocumented anyway. 

Even when it did exist, it appears it returned the time associated with the page,  not the current time. So cachebuster would not have been working anyway.

Possible solution is to make a pull request to hugo adding a "now" function that returns `time.Now()`.
This is the related code in hugo: https://github.com/spf13/hugo/blob/master/tpl/template_funcs.go#L2018
I'll get to it in a couple of days!

I'll disable cachebuster by default in `config.toml` until we can sort this out.

**Comment by nishanths** [comment]
dependent on hugo pr: https://github.com/spf13/hugo/pull/2859

**Comment by nishanths** [comment]
Done in https://github.com/nishanths/cocoa-hugo-theme/commit/2e598e5b739c0529ba0d8ec305066ad209f4317f.

works for me with hugo 0.18. 
@robinst please feel free to reopen if you have issues. thanks for patience!

Related thread for future: https://discuss.gohugo.io/t/proposal-replace-page-now/4968
