### ISSUE TITLE
Replace icon font with SVG icons?

### ISSUE THREAD

**Issue by robinst** [nishanths/cocoa-hugo-theme#45]
The theme currently uses the [ionicon icon font](http://ionicons.com/), which results in 230 KB of `.css` and `.ttf`. For the few icons that are actually used from it, this seems like a significant addition to the page weight.

Have you considered replacing them with SVG icons instead? [Simple icons](https://simpleicons.org/) look promising, I found all icons that are referenced in `header.html`, and they're typically between 500 bytes and 1 KB.

I can prepare a PR for this if you like the idea (or even if you're unsure about it).

**Comment by nishanths** [comment]
SVG would be great. Thanks for preparing a PR!

**Comment by nishanths** [comment]
Fixed by #47
