### ISSUE TITLE
Is `relativeurls        = true` supposed to work?

### ISSUE THREAD

**Issue by daviddias** [nishanths/cocoa-hugo-theme#56]
I'm being unable to get relativeurls to work with this theme, is it supposed to work?

Ref: https://gohugo.io/extras/urls/

**Comment by nishanths** [comment]
Adding `relativeurls = true` works for me in `exampleSite`. For instance, the page `http://localhost:1313/blog/metamorphosis-by-franz-kafka/` has the "About" link as a relative url.

Do you have an example where it doesn't?

**Comment by nishanths** [comment]
I cloned the repo, then ran:

```
$ cd exampleSite
$ git clone git@github.com:nishanths/cocoa-hugo-theme.git themes/cocoa
$ vim config.toml # added "relativeurls = true" 
$ cat config.toml # some output elided
baseurl             = "https://you.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Arthur Dent"
title               = "Arthur Dent"
pygmentsuseclasses  = true
disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"
relativeurls = true

[permalinks]
...
$ hugo serve -t cocoa --watch
```

Then visited `http://localhost:1313/blog/metamorphosis-by-franz-kafka/` and inspected the `body > section.header > div > div > nav > ul > li.nav-about > a` element.

**Comment by daviddias** [comment]
Interesting, I was unable to get CSS to load correctly with it, here is the code and the page loaded to IPFS:

- code https://github.com/diasdavid/daviddias.me/tree/hugo
- published at http://ipfs.io/ipfs/QmdFv5Y11ecBTum6xnKhdMqGDBA6ecHANkSjevB7pF8t9P/

I've been successful using another hugo theme, which can be seen at: http://blog.daviddias.me/

**Comment by nishanths** [comment]
```
<link rel="stylesheet" href="../css/reset.css?t=1486878938">
```

It's unable to find the CSS files because of the query portion `?t=<timestamp>`. A web server would be able to serve them usually, but perhaps using relative URLs makes it not work.

The timestamp exists for cache busting. You can disable it by setting in `config.toml`:

```
cachebuster = false
```

This should remove the `?t=<timestamp>` portion.

**Comment by daviddias** [comment]
Just tried it: https://ipfs.io/ipfs/QmcsoyYrz4qK9q25z2ciAgErM1tcbf3sZiAqarhUwFB2Hp/blog/webrtc-explorer-2-0-0-alpha-release/ and it doesn't seem to make the trick, any other tips?

The url in html looks right, but then the request goes to another place:
![image](https://cloud.githubusercontent.com/assets/1211152/22860068/e174a71e-f0a6-11e6-9e81-6ddf861c1c7d.png)

**Comment by nishanths** [comment]
The file `layouts/partials/head.html` does:

```
<base href="{{ .Site.BaseURL }}">
```

The base URL is specified here in config.toml. https://github.com/diasdavid/daviddias.me/blob/hugo/config.toml#L1

In this case, I think the base URL should be: `https://ipfs.io/ipfs/QmdFv5Y11ecBTum6xnKhdMqGDBA6ecHANkSjevB7pF8t9P/`

**Comment by daviddias** [comment]
Got it! The base url needs to be `""`, in my previous blog with hugo, `"/"` was the thing to make it work, here seems to be `""` which makes more sense.

I wouldn't be able to select the baseURL that way, since it is the hash of the content in a Directed and Acyclic Graph (can't point to itself).

This works for me, thank you! :)

**Comment by nishanths** [comment]
glad to help!
