### ISSUE TITLE
Possible typo in markdown.less: em instead of rem

### ISSUE THREAD

**Issue by lpancescu** [nishanths/cocoa-hugo-theme#63]
Hi,

While reading the source, I noticed that the `font-size` for `h3` is the only one set in `em`, while all the other heading styles are specified in `rem`. Is this perhaps a typo?

https://github.com/nishanths/cocoa-hugo-theme/blob/master/dev/less/markdown.less#L27

**Comment by nishanths** [comment]
yes, it's a typo

**Comment by nishanths** [comment]
happy to merge a fix!

**Comment by nishanths** [comment]
fixed via #64
