### ISSUE TITLE
Support multilingual sites

### ISSUE THREAD

**Issue by lpancescu** [nishanths/cocoa-hugo-theme#67]
Would it be possible to add multilingual support to Cocoa? I already have a functional implementation in the `i18n` branch of `lpancescu/cocoa-hugo-theme`, but I'm not sure how you would like to switch between the languages. Perhaps country flags as SVGs, near the other icons?

I can also send it as a PR, if you prefer that for easier discussion.

**Comment by nishanths** [comment]
I'd be thrilled to see this implemented! Yes, country flags sounds good. Ideally, we should include an option in `config.toml` (a boolean is fine) to show/hide the flags.

**Comment by lpancescu** [comment]
@nishanths I thought I could resize the flags to a maximum of 16x16 size, to be consistent with the existing icons in the theme (Wikipedia has public domain SVG flags - *gemeinfrei* in German). The German and French flags, which use big colored stripes, are still looking acceptable, but flags with higher levels of detail like the USA or the UK ones don't look nice at this size, especially on non-retina displays. The aspect ratio is also different for each country, so they're not looking nice when you have more than one in a row. The USA flag is the longest, for a given height. I also found an existing repo with public-domain SVG flags for lots of countries. https://github.com/hjnilsson/country-flags

I put 4 such 16x16 flags under https://github.com/lpancescu/cocoa-hugo-theme/tree/i18n-flags/static/img/flags if you want to take a look.

The alternative would be to use plain text:
> Translations: [de]() \[**en**\] [fr]()

What do you think?

**Comment by lpancescu** [comment]
@nishanths I have a first implementation of country flags for switching between languages - I clipped a relevant square portion of the flags, and applied rounded corners. I included two screenshots with German and English text in the README:

https://github.com/lpancescu/cocoa-hugo-theme/blob/i18n-flags/README.md#switch-between-languages

**Comment by nishanths** [comment]
❤️ the flags @lpancescu, happy to merge as is!

**Comment by lpancescu** [comment]
Implemented in PR #70, closing.

**Comment by ghost** [comment]
I have problem with enabling the `de` language. How do you do it? I enabled the `i18n_flags` in config file. What else is needed at this point? You have to set language in each, separate post / page or maybe it is possible to change default theme language too?
