### ISSUE TITLE
Per page, blog post meta description

### ISSUE THREAD

**Issue by resoltico** [nishanths/cocoa-hugo-theme#68]
Hey!

I'd like to ask please to make it possible for an individual blog posts and pages to have their own meta description.

Currently only the site-wide description is processed:

``
{{ if .Site.Params.description }}<meta name="description" content="{{ .Site.Params.description }}">{{ end }}
``

Thanks!

**Comment by robinst** [comment]
Somewhat related, here's a PR adding OpenGraph meta tags, for Twitter and others: https://github.com/nishanths/cocoa-hugo-theme/pull/69

**Comment by lpancescu** [comment]
@strauhmanis Is PR #80 missing anything you wanted for per-page meta description? If not, I would propose closing this issue.

**Comment by resoltico** [comment]
@lpancescu this looks great. Thank you! Please close the issue.
