### ISSUE TITLE
"back to posts" link does not redirect to blog posts

### ISSUE THREAD

**Issue by teekaay** [nishanths/cocoa-hugo-theme#86]
Hey, thanks for this amazing theme!
When I press the "back to posts" Link in a blog post (e.g. `/blog/my-post/`) I am redirected to
`/blog` which renders a blank page. In `layouts/blog/single.html` maybe the following should be changed:

     <p><a href="/blog/">{{ i18n "backToPosts" }}</a></p>     

to

     <p><a href="/">{{ i18n "backToPosts" }}</a></p>     

so that I am back to my start page after clicking the link. Or do I configured something wrong?

**Comment by lpancescu** [comment]
It's probably your configuration. The example site works fine:

    mkdir -p $TMPDIR/site
    cd $TMPDIR/site
    git clone https://github.com/nishanths/cocoa-hugo-theme.git themes/cocoa
    (cd themes/cocoa && cp -a exampleSite/ ../..)
    hugo serve -w
