### ISSUE TITLE
Support for markdown bulleted identation

### ISSUE THREAD

**Issue by daviddias** [nishanths/cocoa-hugo-theme#96]
Hi @nishanths! Still a great fan of your theme and the one I continue to use for my website.

One quick question, why the lack of support for indentation on markdown bullets, such as:

- a
  - 1 
  - 2
  - 3
- b

```
- a
  - 1 
  - 2
  - 3
- b
```

cocoa is rendering it as a flat list for me.

Thanks!

**Comment by nishanths** [comment]
Thanks for reporting! Poor CSS on my part. Will take a look soon; happy to merge a PR that fixes this as well.

**Comment by nishanths** [comment]
This should have been fixed around a month ago with these 2 commits: https://github.com/nishanths/cocoa-hugo-theme/commit/c78ef11d95458932eb7ec70a72e8326bc9212347, https://github.com/nishanths/cocoa-hugo-theme/commit/ded90f8ba3fff687113c457d62d94152c7b5b9d9. Please re-open if that didn't fix it.

**Comment by daviddias** [comment]
Thanks @nishanths :)
